#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path


def has_module(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


def has_binary(name: str) -> str | None:
    return shutil.which(name)


def path_exists(path: str) -> bool:
    return Path(path).exists()


def check_chrome() -> str | None:
    candidates = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
    ]
    return next((item for item in candidates if Path(item).exists()), None)


def command_version(command: list[str]) -> str | None:
    try:
        proc = subprocess.run(command, check=False, capture_output=True, text=True, timeout=8)
    except (OSError, subprocess.SubprocessError):
        return None
    text = (proc.stdout or proc.stderr).strip().splitlines()
    return text[0] if text else None


def status(ok: bool, label: str, detail: str = "") -> dict[str, object]:
    return {"ok": ok, "label": label, "detail": detail}


def main() -> int:
    python_version = ".".join(map(str, sys.version_info[:3]))
    pandoc_path = has_binary("pandoc")
    textutil_path = has_binary("textutil")
    chrome_path = check_chrome()
    pixelrag_repo = Path("/Users/alex/Documents/myWork/openCode/PixelRAG")
    pixelrag_learning = Path("/Users/alex/Documents/myWork/openCode/praxis-learning/projects/PixelRAG.md")

    checks = {
        "core": [
            status(sys.version_info >= (3, 10), "Python 3.10+", python_version),
            status(True, "Document package scripts bundled", str(Path(__file__).resolve().parent)),
            status((Path(__file__).resolve().parent / "pixelrag_prepare.py").exists(), "PixelRAG handoff script", "pixelrag_prepare.py"),
            status(True, "Default export root", "<WORKSPACE>/document-exports"),
        ],
        "pdf_input": [
            status(has_module("pdfplumber"), "pdfplumber module", "preferred PDF text extraction"),
            status(has_module("pypdf"), "pypdf module", "fallback PDF text extraction"),
        ],
        "human_outputs": [
            status(True, "readable.html", "always generated by bundled scripts"),
            status(bool(pandoc_path), "pandoc", pandoc_path or "optional; install with: brew install pandoc"),
            status(bool(textutil_path), "macOS textutil", textutil_path or "fallback DOCX conversion unavailable"),
            status(has_module("docx"), "python-docx module", "optional; useful for richer DOCX generation"),
            status(bool(chrome_path), "Chrome/Edge/Chromium", chrome_path or "optional; used for HTML to PDF fallback"),
        ],
        "visual_rag": [
            status(pixelrag_repo.exists(), "PixelRAG local repository", str(pixelrag_repo) if pixelrag_repo.exists() else "optional follow-up indexer; not bundled"),
            status(pixelrag_learning.exists(), "PixelRAG learning note", str(pixelrag_learning) if pixelrag_learning.exists() else "optional"),
        ],
    }

    print("praxis-document-export environment check")
    print(f"Python: {python_version}")
    print("")
    for group, items in checks.items():
        print(group + ":")
        for item in items:
            icon = "✅" if item["ok"] else "⚠️"
            detail = f" — {item['detail']}" if item["detail"] else ""
            print(f"  {icon} {item['label']}{detail}")
        print("")
    print("JSON:")
    print(json.dumps(checks, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
